name: Build Project

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      node_version:
        description: 'Node.js version'
        required: false
        default: '18'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version || '18' }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Create .env file
        run: echo "${{ secrets.DOTENV_FILE }}" > .env

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build
